database:
  host: "185.207.166.19"
  port: 1028
  database: "s7034_nexustags"
  username: "u7034_BQX3UNLeSD"
  password: "I5X4tvHS^D.Nxh7DMX7R16vO"

economy:
  balance_placeholder: "%nexogems_balance%"
  withdraw_command: "nb withdraw %player% %price% Purchase Tag %tag%"